/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DShortIDIndexImport } from './routes/d/$shortID/index'
import { Route as DShortIDModelIndexImport } from './routes/d/$shortID/model/index'
import { Route as DShortIDModelModelEntryIndexImport } from './routes/d/$shortID/model/$model/entry/index'
import { Route as DShortIDModelModelEntryEntryIDImport } from './routes/d/$shortID/model/$model/entry/$entryID'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const DIndexLazyImport = createFileRoute('/d/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const DIndexLazyRoute = DIndexLazyImport.update({
  path: '/d/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/d/index.lazy').then((d) => d.Route))

const DShortIDIndexRoute = DShortIDIndexImport.update({
  path: '/d/$shortID/',
  getParentRoute: () => rootRoute,
} as any)

const DShortIDModelIndexRoute = DShortIDModelIndexImport.update({
  path: '/d/$shortID/model/',
  getParentRoute: () => rootRoute,
} as any)

const DShortIDModelModelEntryIndexRoute =
  DShortIDModelModelEntryIndexImport.update({
    path: '/d/$shortID/model/$model/entry/',
    getParentRoute: () => rootRoute,
  } as any)

const DShortIDModelModelEntryEntryIDRoute =
  DShortIDModelModelEntryEntryIDImport.update({
    path: '/d/$shortID/model/$model/entry/$entryID',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/d/': {
      preLoaderRoute: typeof DIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/d/$shortID/': {
      preLoaderRoute: typeof DShortIDIndexImport
      parentRoute: typeof rootRoute
    }
    '/d/$shortID/model/': {
      preLoaderRoute: typeof DShortIDModelIndexImport
      parentRoute: typeof rootRoute
    }
    '/d/$shortID/model/$model/entry/$entryID': {
      preLoaderRoute: typeof DShortIDModelModelEntryEntryIDImport
      parentRoute: typeof rootRoute
    }
    '/d/$shortID/model/$model/entry/': {
      preLoaderRoute: typeof DShortIDModelModelEntryIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  DIndexLazyRoute,
  DShortIDIndexRoute,
  DShortIDModelIndexRoute,
  DShortIDModelModelEntryEntryIDRoute,
  DShortIDModelModelEntryIndexRoute,
])

/* prettier-ignore-end */
