import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { entryList } from "../lib/entries";

function cleanItem(item: any) {
  if (!item || typeof item !== "object") return item;
  const { _links, _embedded, ...rest } = item;
  return rest;
}

export async function record(opts: {
  dm: string;
  env: string;
  out: string;
  token: string;
  models: string[];
  count: number;
}) {
  const { dm, env, out, token, models, count } = opts;

  process.stderr.write(`Recording fixtures for datamanager ${dm}...\n`);

  const entries: Record<string, any[]> = {};

  for (const model of models) {
    process.stderr.write(`  ${model}...\n`);
    try {
      const result = await entryList({ env, dmShortID: dm, model, token, options: { size: count } });
      entries[model] = result.items.map(cleanItem);
      process.stderr.write(`  ${model}: ${entries[model].length} entries\n`);
    } catch (e: any) {
      process.stderr.write(`  Warning: could not fetch entries for ${model}: ${e.message}\n`);
      entries[model] = [];
    }
  }

  const cmdParts = ["ec.fdk record", `--dm ${dm}`, `--env ${env}`, `--size ${count}`];
  if (out !== `./ec.fdk.fixtures.${dm}.ts`) cmdParts.push(`--out ${out}`);
  cmdParts.push(`--models ${models.join(",")}`);
  const cmd = cmdParts.join(" ");

  const modelLines = models.map((model) => {
    const data = JSON.stringify(entries[model], null, 2).replace(/\n/g, "\n  ");
    return `  ${model}: ${data} as TypedEntry<'${model}'>[],`;
  });

  const content = `// Generated by ec.fdk record — do not edit manually
// Regenerate: ${cmd}
import type { TypedEntry } from 'ec.fdk';

export const fixtures = {
${modelLines.join("\n")}
};
`;

  const outPath = resolve(out);
  writeFileSync(outPath, content, "utf-8");
  process.stderr.write(`\nGenerated ${outPath} with ${models.length} model(s).\n`);
}
