/** Maps entrecode schema field types to TypeScript type strings */
export const schemaTypeToTS: Record<string, string> = {
  text: "string",
  formattedText: "string",
  string: "string",
  url: "string",
  email: "string",
  phone: "string",
  number: "number",
  decimal: "number",
  boolean: "boolean",
  datetime: "Date",
  json: "Record<string, any>",
  object: "Record<string, any>",
  entry: "string",
  entries: "string[]",
  asset: "string",
  assets: "string[]",
  location: "{ latitude: number; longitude: number }",
  account: "string",
  role: "string",
  date: "string",
  period: "string",
};
